server:
    port: 8862
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: cloud-palletbox-client
    jackson:
        property-naming-strategy: SNAKE_CASE
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
        sentinel:
            transport:
                port: 18763
                dashboard: localhost:8748
feign:
    sentinel:
        enabled: true