server:
    port: 8860
spring:
    main:
        ## @FeignClient(value = "服务名r") 设置可以有多个类存在相同的FeignClient 中的value值
        allow-bean-definition-overriding: true
    application:
        name: cloud-palletbox-admin
    jackson:
        property-naming-strategy: SNAKE_CASE
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
        sentinel:
            transport:
                port: 18763
                dashboard: localhost:8748
feign:
    sentinel:
        enabled: true