server:
    port: 8866
    base-path: ./upload/
spring:
    main:
        allow-bean-definition-overriding: true
    application:
        name: cloud-palletbox-upload
    jackson:
        property-naming-strategy: SNAKE_CASE
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
        sentinel:
            transport:
                port: 18763
                dashboard: localhost:8748
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
feign:
    sentinel:
        enabled: true